networks:
  shared_network:
    driver: bridge

services:

  # Telegram bot service
  bot:
    container_name: bot
    build:
      target: prod-build
      context: ..
      dockerfile: backend/bot/Dockerfile
    env_file:
      - .env.prod
    volumes:
      - ../backend/infrastructure/migrations/versions:/app/infrastructure/migrations/versions
      - ../data:/app/data
    restart: unless-stopped
    networks:
      - shared_network

  # PostgreSQL database for bot
  postgres:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES__DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB_NAME}
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__DB_USER} -d ${POSTGRES__DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shared_network

  # Dozzle
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - shared_network

volumes:
  database_volume:

